version: "3.7"
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: project
        ports:
            - 27017:27017
        networks:
            - mongo-compose-network
        volumes:
            - mongodb_data_container:/data/db
    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        restart: always
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_SERVER: mongodb
        ports:
            - 5001:8081
        networks:
            - mongo-compose-network
        volumes:
            - mongodb_data_container:/data/db

volumes:
    mongodb_data_container:

networks:
  mongo-compose-network:
    driver: bridge