name: CI Tests
on:
  push:
    branches:
      - Backend
      - dev
      - main

jobs:
  TestCI:
    name: TestsCI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker
        run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Start docker
        run: docker-compose up -d
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test:ci